# Generated by Django 4.1.7 on 2023-03-19 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('category', models.CharField(blank=True, choices=[('Earrings', 'Earrings'), ('EarClimbers', 'EarClimbers')], max_length=191)),
                ('type', models.CharField(blank=True, choices=[('Studs', 'Studs'), ('Cuffs', 'Cuffs'), ('Gemstone', 'Gemstone')], max_length=191)),
                ('style', models.CharField(blank=True, choices=[('basic', 'basic'), ('fancy', 'fancy')], max_length=191)),
                ('color', models.CharField(blank=True, choices=[('silver', 'silver'), ('gold', 'gold')], max_length=191)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, upload_to='product_images/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.productitem')),
            ],
        ),
    ]
