# Generated by Django 4.1.7 on 2023-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='album',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
