# Generated by Django 4.1.7 on 2023-03-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='album',
            new_name='image',
        ),
    ]
